/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 laptop.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.027}>
        <group position={[-0.03, 111.687, 2.841]} scale={3.371}>
          <mesh geometry={nodes.Screen.geometry} material={materials.Namibia} position={[0.009, -33.128, -0.843]} scale={0.297} />
          <mesh geometry={nodes.Black_Inset.geometry} material={materials['Display Rim 1']} position={[0.009, -33.128, -0.843]} scale={0.297} />
          <mesh geometry={nodes.Rubber.geometry} material={materials['Display Rubber 1']} position={[0.009, -33.128, -0.843]} scale={0.297} />
          <mesh geometry={nodes.Screen_Back.geometry} material={materials['Body 2']} position={[0.009, -33.128, -0.843]} scale={0.297} />
        </group>
        <mesh geometry={nodes.Keyboard.geometry} material={materials['Keyboard 2']} />
        <mesh geometry={nodes.Touch_Panel.geometry} material={materials['Touch Bar 1']} />
        <mesh geometry={nodes.Ports.geometry} material={materials['Ports 1']} />
        <mesh geometry={nodes.Touchpad.geometry} material={materials['Touchpad 1']} />
        <mesh geometry={nodes.Body.geometry} material={materials['Body 3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
